### ISSUE TITLE
Frage: Sichere Docker images für cloud Anwendungen erstellen

### ISSUE THREAD

**Issue by siredmar** [andre2007/d-land#25]
Danke fuer das Tutorial! 
Eine Frage hab ich aber: Binaries koennen zur Laufzeit Libraries laden. Diese sind mit ldd vor Prozessstart leider nicht sichtbar. Ausser den Prozess zu starten und zu schauen welche Libraries geladen sind, faellt mir nichts ein. Hast du dazu Ideen?

**Comment by andre2007** [comment]
Diesen Fall hab ich tatsächlich auch in einem meiner Projekte. Ich kenne die `.so` Dateien die zur Laufzeit geladen werden. Ich kopiere diese einzeln mit dem Befehl `cp` nach `/dist/lib`, `/dist/usr/lib/`, ...
Damit stehen sie dann im scratch Image zur Verfügung.

**Comment by siredmar** [comment]
Danke!
